### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by thbar** [thbar/ex-portmidi#9]
While working on Big Sur (11.6), on a new M1 machine, I am meeting the following error:

```
❯ make
cc -g -std=c99 -O3 -pedantic -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -I/Users/thbar/.asdf/installs/erlang/24.0.3/erts-12.0.3/include -fPIC -shared -dynamiclib -undefined dynamic_lookup -o priv/portmidi_in.so -lportmidi src/portmidi_in.c src/portmidi_shared.c
src/portmidi_in.c:3:10: fatal error: 'portmidi.h' file not found
#include <portmidi.h>
         ^~~~~~~~~~~~
1 error generated.
src/portmidi_shared.c:1:10: fatal error: 'portmidi.h' file not found
#include <portmidi.h>
         ^~~~~~~~~~~~
1 error generated.
make: *** [priv/portmidi_in.so] Error 1
```

This is despite having run `brew install portmidi`, which used to be enough for the installation to work.

Interestingly, the CI (see #8) does not appear to face the same issue, so I'll compare the logs.

**Comment by thbar** [comment]
Closed via #10
